version: '3.1'

services:
    mariadb:
        image: mariadb-img
        container_name: mariadb
        build: "requirements/mariadb/"
        env_file:
            - .env
        expose:
            - "3306"
        volumes:
            - mariadb:/var/lib/mysql/
        restart: always

    wordpress:
        image: wordpress-img
        build: "requirements/wordpress/"
        container_name: wordpress
        depends_on:
            - mariadb
        volumes:
            - /Users/umartin-/Documents/data/wordpress:/var/www/html
        expose:
            - "9000"
        networks:
            - inception-net
        restart: always
        env_file:
            - .env

    nginx:
        build: "requirements/nginx/"
        container_name: nginx
        ports:
            - "443:443"
        expose:
            - "9000"
        volumes:
            # - wordpress:/var/www/html
            - /Users/umartin-/Documents/data/wordpress:/var/www/html
        depends_on:
            - wordpress
        networks:
            - inception-net
        env_file:
            - .env
        restart: always

networks:
    inception-net:
        driver: bridge

volumes:
    wordpress:
        driver: local
        driver_opts:
            type: volume
            device: /home/umartin-/Documents/data/wordpress
            o: bind
    mariadb:
        driver: local
        driver_opts:
            type: none
            device: /Users/umartin-/Documents/data/DB
            o: bind